### ISSUE TITLE
how to disable uvicorn / fastapi default logging

### ISSUE THREAD

**Issue by oieduardorabelo** [Kludex/fastapi-tips#23]
thanks for the initiative @Kludex 

one question that i struggle to find a solid answer + i saw many horrors in the wild trying to do it:

how to disable the default logs from uvicorn / fastapi

and now with the fastapi cli `fastapi dev ..` / `fastapi run ..`

how to achieve the "unix rule of silence", if is running correctly, no logs are displayed?

![CleanShot 2024-07-23 at 01 11 16](https://github.com/user-attachments/assets/cee81dd0-f6bd-471f-82fe-7c119320bbc1)

**Comment by Kludex** [comment]
My recommendation is to use Uvicorn directly.
