### ISSUE TITLE
uvloop is not supported on windows

### ISSUE THREAD

**Issue by the-code-rider** [Kludex/fastapi-tips#7]
# issue
i tried installing uvloop on my machine windows 11; python 3.10.0. i have added the error message in the screenshot. 
it was bit of a bummer, considering that this is the first tip and is not supported in windows. while i can probably install it while building the docker image, i don't want to keep docker and local setup different.  
 
![image](https://github.com/Kludex/fastapi-tips/assets/143208377/826745c8-7a3b-4813-b5ea-37e4ce960997)

# suggested solution
should we perhaps add a warning in the doc, or will it look ugly/unnecessary?

**Comment by Kludex** [comment]
Well... I usually forget Windows users. 😬

Maybe a warning like:

> [!WARNING]
> `uvloop` can't be installed on Windows. If you use Windows locally, but Linux based system on production, you can use an [environment marker](https://peps.python.org/pep-0496/) to not install `uvloop` on Windows e.g. `uvloop; sys_platform != 'win32'`.

PR welcome.

**Comment by the-code-rider** [comment]
submitted a pr https://github.com/Kludex/fastapi-tips/pull/8

on a lighter note: 

![hidethepain](https://github.com/Kludex/fastapi-tips/assets/143208377/8f6f762c-3cdd-4666-ac8d-769f6a8f54c4)
